dist: trusty
language: tex
sudo: false

env:
  - DOCUMENT_NAME=Test

install:
  - cp -n texlive* /tmp/
  - source /tmp/texlive_install.sh
  - tlmgr install koma-script etoolbox logreq biblatex-apa

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
  - pdflatex -interaction=nonstopmode -halt-on-error ${DOCUMENT_NAME}.tex
  - biber *.bcf
  - pdflatex -interaction=nonstopmode -halt-on-error ${DOCUMENT_NAME}.tex
  - pdflatex -interaction=nonstopmode -halt-on-error ${DOCUMENT_NAME}.tex
